name: Compile EPUB
on:
  push:
  pull_request:
      types: [closed]
jobs:
  Compile-Epub:
    env:
      filename: recipes.epub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Remove old EPUB
        shell: bash
        run: rm -f ${{ env.filename }}
      - name: Compile EPUB
        shell: bash
        run: zip -0Xq ${{ env.filename }} mimetype; zip -Xr9Dq ${{ env.filename }} META-INF/ && zip -Xr9Dq ${{ env.filename }} OEBPS/
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor}}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add ${{ env.filename }}
          git commit -am "Compiled EPUB based on commit ${{ github.sha }} from branch '${{ github.ref_name }}'"
          git push
