name: Compile EPUB
on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  compile-epub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Remove previous EPUB version
        run: rm -f ${GITHUB_WORKSPACE}/recipes.epub

      - name: Compile new EPUB
        run: |
          zip -0Xq ${GITHUB_WORKSPACE}/recipes.epub ${GITHUB_WORKSPACE}/mimetype
          zip -Xr9Dq ${GITHUB_WORKSPACE}/recipes.epub ${GITHUB_WORKSPACE}/META-INF/
          zip -Xr9Dq ${GITHUB_WORKSPACE}/recipes.epub ${GITHUB_WORKSPACE}/OEBPS/
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'sch0lars'
          git config --global user.email 'sch0lars@users.noreply.github.com'
          git add ${GITHUB_WORKSPACE}/recipes.epub
          git commit -m "Compiled Latest Version of EPUB"
          git push
